version: "3.8"

services:
  onedev-app:
    image: "1dev/server:latest"
    container_name: "onedev-app"
    restart: unless-stopped
    environment:
      - hibernate_dialect=io.onedev.server.persistence.PostgreSQLDialect
      - hibernate_connection_driver_class=org.postgresql.Driver
      - hibernate_connection_url=jdbc:postgresql://onedev-db:5432/onedevdb
      - hibernate_connection_username=onedevusr
      - hibernate_connection_password=onedev
    volumes:
      - ./data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6610:6610"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:latest"
    container_name: "onedev-db"
    restart: "unless-stopped"
    environment:
      - PGUSER=onedevusr
      - POSTGRES_USER=onedevusr
      - POSTGRES_PASSWORD=onedev
      - POSTGRES_DB=onedevdb
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onedevusr -d onedevdb"]
      interval: 5s
      timeout: 5s
      retries: 60
